[workspace]
authors = ["Mathew Chu <mchu001.bio@gmail.com>"]
channels = ["conda-forge"]
name = "crime-vs-surveillance"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
pandas = ">=2.2.3,<3"
openpyxl = ">=3.1.5,<4"
matplotlib = ">=3.9.2,<4"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
scipy = ">=1.13.1,<2"
plotly = ">=5.24.1,<6"
statsmodels = ">=0.14.0,<1.0"

[tasks]
clean = "python src/clean_data.py"
merge = "python src/merge_data.py"
analyze = "python src/analysis_and_plot.py"
all = { depends-on = ["clean", "merge", "analyze"] }
